import React from 'react';
import { Link } from 'react-router-dom';
import './LegalPage.css';

export default function Privacy() {
  return (
    <div className="legal-page">
      <div className="legal-page__card">
        <Link to="/login" className="ghost-link">← Back to login</Link>
        <h1>Privacy Policy</h1>
        <p className="legal-page__updated">Last updated: {new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' })}</p>

        <p>
          RentaPay is a Kenya-based rent management platform used by landlords, property
          managers, caretakers, and tenants. This Privacy Policy explains what personal
          information we collect, why we collect it, how it is used and shared, how long we
          keep it, and the choices and rights you have over it. It should be read alongside our{' '}
          <Link to="/terms">Terms of Service</Link>.
        </p>
        <p>
          We process personal data in a way that is intended to be consistent with Kenya's Data
          Protection Act, 2019, and the guidance of the Office of the Data Protection
          Commissioner. If you have questions this policy doesn't answer, see Section 10 for how
          to contact us.
        </p>

        <h2>1. Who This Policy Covers</h2>
        <p>
          This policy applies to anyone who creates or is added to a RentaPay account —
          landlords, property managers, caretakers, and tenants — as well as to prospective
          tenants who browse RentaPay's public vacant-unit listings without an account, and to
          anyone who contacts a landlord through the public listing page's WhatsApp integration.
        </p>

        <h2>2. Information We Collect</h2>
        <h3>2.1 Information you or your landlord/manager provide</h3>
        <ul>
          <li>Full name, phone number, and email address, for landlords, property managers,
            caretakers, and tenants;</li>
          <li>National ID number and emergency contact details, where a landlord requests them
            from a tenant as part of onboarding;</li>
          <li>Property and unit details, including addresses, rent amounts, due dates, unit
            photos, and lease start/move-in dates;</li>
          <li>Payment records, including M-Pesa transaction codes, amounts, timestamps, and
            payment method;</li>
          <li>Content you submit through the platform's features, such as maintenance requests,
            complaints, dispute descriptions, community board posts and replies, and ratings
            (including optional written comments attached to a rating);</li>
          <li>Account credentials (your password is stored as a one-way cryptographic hash — we
            cannot see or recover your actual password).</li>
        </ul>
        <h3>2.2 Information generated by your use of the platform</h3>
        <ul>
          <li>Login timestamps, session activity, and basic device/browser information used for
            security purposes (e.g. detecting suspicious login attempts);</li>
          <li>Records of notifications sent to you (email and, where enabled, WhatsApp), so we
            can confirm delivery and avoid duplicate sends;</li>
          <li>A tenant's aggregate rating history, computed from ratings submitted by landlords,
            managers, and caretakers who have managed that tenant, keyed to the tenant's email
            address so it can be portable across landlords at the tenant's choice.</li>
        </ul>
        <h3>2.3 Information from third parties</h3>
        <p>
          When a landlord pays their RentaPay subscription via M-Pesa STK push, Safaricom provides
          transaction confirmation data (such as amount, phone number, and M-Pesa receipt number)
          back to RentaPay so that payment can be recorded automatically. Tenant rent payments work
          differently: a tenant pays a landlord directly via M-Pesa (Paybill, Till, or Send Money)
          and then manually enters the transaction code, amount, payer name, payer phone number,
          and M-Pesa SMS time within RentaPay — this information comes from the tenant, not
          automatically from Safaricom, and is reviewed and confirmed by the landlord, manager, or
          caretaker before it's treated as paid.
        </p>

        <h2>3. How We Use Your Information</h2>
        <p>Your information is used to operate the core service, specifically to:</p>
        <ul>
          <li>Create and secure your account, and verify your identity when you log in or reset
            your password;</li>
          <li>Track rent balances, confirm payments, and generate receipts and payment history;</li>
          <li>Send account notifications, payment reminders, receipts, and — for landlords — the
            optional portfolio health digest summarizing occupancy, collections, and vacant
            units missing photos;</li>
          <li>Enable communication between landlords, managers, caretakers, and tenants,
            including maintenance requests, complaints, disputes, and the community board;</li>
          <li>Compute and display tenant reputation scores, and — only at the tenant's own
            choice — generate a shareable link to that tenant's own aggregate score for use when
            contacting a prospective new landlord;</li>
          <li>Display a unit's photos and basic details on RentaPay's public vacant-listing page
            when a landlord marks a unit as publicly listed, and connect an interested tenant to
            the landlord, manager, or caretaker via WhatsApp;</li>
          <li>Detect and prevent fraud, abuse, and violations of our Terms of Service;</li>
          <li>Improve and maintain the platform, including diagnosing technical issues.</li>
        </ul>
        <p>
          Email addresses are used primarily to send account notifications, receipts, reminders,
          password reset codes, and (for landlords who opt in) digest emails. Phone numbers are
          used primarily for account identification, WhatsApp-based contact on public listings,
          and M-Pesa payment processing. <strong>We do not sell your personal data to third
          parties</strong>, and we do not use your data to serve third-party advertising.
        </p>

        <h2>4. Who Can See Your Information</h2>
        <p>
          RentaPay is built around a small number of clearly scoped visibility rules, rather
          than broad access:
        </p>
        <ul>
          <li>A tenant's landlord, and any property managers or caretakers that landlord has
            added to that tenant's property, can see that tenant's account details and payment
            records.</li>
          <li>A tenant can see their own balance, payment history, and their landlord's/manager's
            payment details (so they know where to pay), but cannot see other tenants' records.</li>
          <li>A tenant's individual rating comments are visible only to that tenant, on their own
            account — not to other landlords, including in a reputation summary the tenant
            chooses to share, which shows only the aggregate score and category breakdown.</li>
          <li>Content posted to a property's community board is visible to other tenants and
            landlord-side users of that same community, not to the wider public.</li>
          <li>A unit's photos and basic listing details are visible to the public only if and
            when a landlord marks that unit as publicly listed as vacant; a landlord can remove
            a unit from public listing at any time.</li>
          <li>RentaPay's own team may access account data as needed to operate, troubleshoot,
            investigate abuse reports, and provide support — access is limited to what's needed
            for the task at hand.</li>
        </ul>
        <p>
          We may also disclose information where required by law, such as in response to a valid
          court order or a lawful request from a Kenyan regulatory or law enforcement authority.
        </p>

        <h2>5. Data Retention</h2>
        <ul>
          <li>Active account data (profiles, units, ongoing payment history) is retained for as
            long as the account remains active, to preserve continuity of records for both
            landlords and tenants.</li>
          <li>Payment confirmation submissions (proof-of-payment images, M-Pesa messages
            submitted for review) that have been confirmed or rejected are retained for six
            months by default, after which they are automatically removed, or deleted sooner at
            the landlord's or manager's discretion. The underlying completed-payment record
            (amount, date, status) is retained for ongoing record-keeping even after the
            supporting proof is removed.</li>
          <li>One-time codes (OTPs) used for account verification and password resets expire
            shortly after issue and are not retained beyond their validity window.</li>
          <li>Where an account is deleted (see Section 6), we retain the minimum data necessary
            to comply with legal, tax, or accounting obligations, and to prevent fraud (for
            example, retaining a record that a given phone number was previously associated with
            a terminated account, without retaining the full profile).</li>
        </ul>

        <h2>6. Your Rights and Choices</h2>
        <p>Under the Data Protection Act, 2019, and consistent with how the platform works, you can:</p>
        <ul>
          <li><strong>Access</strong> the personal data we hold about you, largely visible
            directly within your own account (profile, payment history, ratings).</li>
          <li><strong>Correct</strong> most of your own details directly in-app. A small number
            of fields — full name, ID number, move-in date, and your email address — are
            controlled by your landlord/manager (for tenants) or fixed after registration (email,
            for every role), because they anchor your login identity and, for tenants, your
            portable rating history; contact your landlord/manager, or RentaPay support, to
            request a correction to those.</li>
          <li><strong>Request deletion</strong> of your account and associated data, via the
            Help option in the app, through your landlord or property manager (for tenant
            accounts), or by contacting the RentaPay team directly. Some records may be retained
            where required for legitimate record-keeping, fraud prevention, or legal compliance,
            as described in Section 5.</li>
          <li><strong>Object to or restrict</strong> certain processing, such as opting out of
            the optional landlord portfolio digest email at any time from your settings.</li>
          <li><strong>Withdraw consent</strong> for optional features — for example, choosing not
            to generate or share a tenant reputation link, or a landlord choosing not to mark a
            unit as publicly listed.</li>
        </ul>
        <p>
          We will respond to legitimate requests within a reasonable time and in line with our
          obligations under Kenyan data protection law.
        </p>

        <h2>7. Security</h2>
        <p>
          We apply reasonable technical and organizational measures to protect your data,
          including encrypted password storage (passwords are hashed, never stored in plain
          text), role-based access controls so accounts only see what their role permits,
          rate-limiting and lockouts on repeated failed login attempts, and encrypted transport
          (HTTPS) for data sent to and from the platform. No system can be guaranteed
          completely secure, and we encourage you to use a strong, unique password and to keep
          your login credentials confidential.
        </p>

        <h2>8. International Data Transfers</h2>
        <p>
          RentaPay's infrastructure providers may process or store data outside Kenya as part of
          delivering the service (for example, cloud hosting or email delivery infrastructure).
          Where this occurs, we take reasonable steps to ensure such providers offer an adequate
          level of data protection, consistent with the requirements of the Data Protection Act,
          2019.
        </p>

        <h2>9. Children's Privacy</h2>
        <p>
          RentaPay is not directed at, and does not knowingly collect personal data from,
          individuals under 18. If you believe a minor has provided us with personal data,
          please contact us so we can address it.
        </p>

        <h2>10. Changes to This Policy</h2>
        <p>
          We may update this Privacy Policy as the platform evolves — for example, to reflect a
          new feature that processes data differently, or a change in applicable law. Where a
          change is material, we will make reasonable efforts to notify account holders in-app
          or by email ahead of it taking effect. The "Last updated" date at the top of this page
          reflects the most recent revision.
        </p>

        <h2>11. Contact</h2>
        <p>
          For privacy questions, access or deletion requests, or to exercise any of the rights
          described above, use the Help option in the app or contact the RentaPay team directly.
        </p>
      </div>
    </div>
  );
}
